### ISSUE TITLE
IAP Samples - Outdated JWT package

### ISSUE THREAD

**Issue by iamacarpet** [GoogleCloudPlatform/php-docs-samples#875]
Hello,

We are using IAP and want to validate the JWTs

I noticed in your examples, the package you are using is abandoned.

https://packagist.org/packages/spomky-labs/jose

It looks like there is a replacement, but it is a lot harder to use with poor documentation, so an example of proper usage would be super helpful.

Once you've got that, would it be possible for us to contribute a Laravel middleware for user sessions based on IAP JWTs?

The current example isn't even a web based example, it's a CLI tool accepting a copy/pasted JWT as a parameter, which isn't super helpful.

Regards,
iamacarpet

**Comment by bshaffer** [comment]
Yes please, any samples for Laravel integration would be very useful!

I will take a look at the JSON signing package.

**Comment by bshaffer** [comment]
@iamacarpet I have fixed the JWT validation by moving to a different library which is much less complicated AND has looser PHP requirements (hooray!). Please open another issue if you have any questions, and feel free to contribute an example for Laravel middleware!

Possibly the best way for you to contribute would be over at https://cloud.google.com/community, or just open a new issue when you've completed your integration and we can work together from there.

Thanks for reporting this issue and for your contributions!

**Comment by iamacarpet** [comment]
Thanks @bshaffer ,

For our own use case, we went with the Users API headers that still exist on requests to the second generation runtimes when behind IAP. Engineering said they didn't see them going away any time soon and it was a much simpler middleware implementation.

That being said, I'll look to add one doing the JWT validation so we've always got a backup if they do disappear and your example looks really straight forward now.

Do you have a recommended way of caching the public keys from that request you are making?

**Comment by bshaffer** [comment]
Hey @iamacarpet!
That sounds reasonable, I'm glad you were able to get it sorted.
For App Engine Standard, I would try file cache (writing to /tmp) using [guzzle cache middleware](https://github.com/Kevinrob/guzzle-cache-middleware).
